name: Trigger Supabase Function Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  invoke_function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST https://xonkffynwuqtggbqgbll.supabase.co/functions/v1/trigger-scheduled-tweets \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvbmtmZnlud3VxdGdnYnFnYmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTk3OTQsImV4cCI6MjA1OTY5NTc5NH0.q709HhfjvwrlteOeUDwHfkvYBXM5Cylf0iCAul-uyJI"

